eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: movie-server
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"

server:
  port: 8083

cinemaService: http://localhost:8085