spring:
  application:
    name: creditcard-server
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"

server:
  port: 8084

authService: http://localhost:8086